# SPDX-License-Identifier: Apache-2.0
"""Graph exports: JSON, Neo4j Cypher and the website's /graph/ snapshot format."""

from __future__ import annotations

import json

from . import __version__
from .model import Graph
from .schema import PATH_STATE, REVIEW_STATE


def to_json(g: Graph) -> str:
    return json.dumps({
        "generator": f"atg-graph {__version__}",
        "review_state": REVIEW_STATE,
        "max_path_state": PATH_STATE,
        "nodes": [{"id": n.id, "type": n.type, "label": n.label, "props": n.props, "provenance": n.provenance}
                  for n in g.nodes.values()],
        "relationships": [{"id": e.id, "from": e.source, "to": e.target, "type": e.type, "props": e.props,
                           "provenance": e.provenance, "review_state": e.review_state} for e in g.edges.values()],
    }, indent=2, sort_keys=False)


def _cy_props(d: dict) -> str:
    items = []
    for k, v in d.items():
        if isinstance(v, (str, int, float, bool)) or (isinstance(v, list) and all(isinstance(x, (str, int, float, bool)) for x in v)):
            items.append(f"`{k}`: {json.dumps(v)}")
    return ", ".join(items)


def to_cypher(g: Graph) -> str:
    """MERGE statements; every element is marked as atg-graph candidate data."""
    lines = ["// Generated by atg-graph. Candidate data for human review, not assessment results.", ""]
    for n in g.nodes.values():
        props = {"label": n.label, "reviewState": REVIEW_STATE, "atgGraph": True,
                 **{k: v for k, v in n.props.items() if k != "basis"}}
        lines.append(f"MERGE (n:`{n.type}` {{id: {json.dumps(n.id)}}}) SET n += {{{_cy_props(props)}}};")
    lines.append("")
    for e in g.edges.values():
        props = {"reviewState": e.review_state, **e.props}
        lines.append(f"MATCH (a {{id: {json.dumps(e.source)}}}), (b {{id: {json.dumps(e.target)}}}) "
                     f"MERGE (a)-[r:`{e.type}` {{id: {json.dumps(e.id)}}}]->(b) SET r += {{{_cy_props(props)}}};")
    return "\n".join(lines) + "\n"


def to_snapshot(g: Graph) -> str:
    """The node/relationship shape the website's GraphExplorer reads."""
    nodes = []
    for n in g.nodes.values():
        auth = n.props.get("authority")
        summary = f"Authority (inferred): {', '.join(auth)}." if auth else ("Authority: UNKNOWN." if n.type in ("MCPCapability", "Tool") else "")
        nodes.append({"id": n.id, "type": n.type, "label": n.label, "summary": (summary + " Candidate, from atg-graph.").strip()})
    rels = [{"id": e.id, "from": e.source, "to": e.target, "type": e.type,
             "conditions": "Candidate relationship from atg-graph; conditions not evidenced."} for e in g.edges.values()]
    return json.dumps({"generatedAt": f"atg-graph {__version__}", "nodes": nodes, "relationships": rels}, indent=2)
