# SPDX-License-Identifier: Apache-2.0
"""Markdown report: candidate findings, the UNKNOWN register and declared facts."""

from __future__ import annotations

from collections import Counter

from . import __version__
from .model import Graph
from .queries import Finding
from .schema import CONTROLS, PATH_STATE, QUESTIONS


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(g: Graph, findings: list[Finding], unknowns: list[dict], context_name: str) -> str:
    out = [
        f"# atg-graph candidate report",
        "",
        f"> Generated by atg-graph {__version__} from `{context_name}`. These are **candidate findings for human review**, "
        "not an AI Trust Graph assessment: no control score, maturity level, Path Exposure Index or conformance claim is "
        f"produced. Every path below is at most **{PATH_STATE}**: it exists in the represented graph, but its conditions, "
        "identities and controls have not been evidenced. Credential values are never read into this report.",
        "",
        "## What was represented",
        "",
    ]
    types = Counter(n.type for n in g.nodes.values())
    preds = Counter(e.type for e in g.edges.values())
    out.append("| Objects | Count |")
    out.append("|---|---|")
    out += [f"| {t} | {c} |" for t, c in sorted(types.items())]
    out += ["", "| Relationships | Count |", "|---|---|"]
    out += [f"| `{p}` | {c} |" for p, c in sorted(preds.items())]

    hits = [f for f in findings if f.items]
    empty = [f for f in findings if not f.items]
    out += ["", f"## Candidate findings ({len(hits)} of {len(findings)} queries returned results)", ""]
    for f in hits:
        out += [f"### {f.query}: {f.title}", "", f.why, ""]
        for it in f.items:
            out.append(f"- **{_cell(it['subject'])}**" + (f": {_cell(it['detail'])}" if it.get("detail") else ""))
            for path in it.get("paths", []):
                out.append("  ```")
                out += [f"  {step}" for step in path]
                out.append("  ```")
        out += ["", "**ATG questions:** " + " ".join(f"{q} *{QUESTIONS[q]}*" for q in f.questions), "",
                "**Relevant controls:** " + "; ".join(f"{c} {CONTROLS[c]}" for c in f.controls), "",
                "**Evidence to collect:**"]
        out += [f"- {e}" for e in f.evidence]
        out.append("")
    if empty:
        out += ["### Queries with no results", "",
                "No result means nothing matched in **what was represented**. It is not evidence that the risk is absent: "
                "inputs can be incomplete.", ""]
        out += [f"- {f.query}: {f.title}" for f in empty]
        out.append("")

    out += ["## UNKNOWN register", "",
            "UNKNOWN means the evidence is absent, insufficient or conflicting. It is never treated as safe, zero, passed or failed.", ""]
    if unknowns:
        out += ["| # | Subject | What is unresolved | Why | Evidence that would resolve it |", "|---|---|---|---|---|"]
        out += [f"| U-{i} | {_cell(u['subject'])} | {_cell(u['what'])} | {_cell(u['why'])} | {_cell(u['resolve'])} |"
                for i, u in enumerate(unknowns, 1)]
    else:
        out.append("No unresolved items were recorded.")
    out += ["", "## Next steps", "",
            "1. Confirm or correct each candidate path with evidence; record the evidence grade (Artifact #6).",
            "2. Resolve the UNKNOWN register, starting with credentials whose reach is unknown.",
            "3. For a full assessment, follow the lifecycle in Artifact #7. For a quick review, use `guides/lite-review.md`.", ""]
    return "\n".join(out)
